version: "3"
services:
  app:
    container_name: app
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - "/app/node_modules"
      - "./app:/app"
  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx
  #   ports:
  #     - "8088:80"
  #   volumes:
  #     - ./backend:/var/www
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php
  #     - db
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: skoly
      MYSQL_USER: docker
      MYSQL_PASSWORD: tajneheslo123
      MYSQL_ROOT_PASSWORD: tajneheslo123
      # SERVICE_TAGS: dev
      # SERVICE_NAME: db
    # volumes:
    #   - db-data:/var/lib/mysql
  php:
    build: ./backend
    container_name: php
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
# volumes:
#   db-data: ~
